name: Test CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Load Environment Variables from .env
        run: |
          if [ -f .env ]; then
            echo "Loading .env file"
            export $(grep -v '^#' .env | xargs)
          else
            echo ".env file not found, skipping"
          fi

      - name: Install Dependencies
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI}}
        run: npm ci

      - name: Run Build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
        run: npm run build

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI}}
        run: npm run test
